config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/desearch'
  get 'cards/new'
  get 'users/show'
  get 'messages/new'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'streets', to: 'users/registrations#new_streeet'
    post 'streets', to: 'users/registrations#create_street'
  end
  root to: "items#index"
  resources :items do
   resources :messages, only: :create
   resources :orders, only: [:index,:create]
   collection do
    get 'search'
    get 'research'
    get 'desearch'
    get 'sosearch'
   end
  end
  resources :users, only: [:show, :update]
  resources :cards, only: [:new, :create]
  resources :items, only: :order do
    post 'order', on: :member
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_one :address
  belongs_to :user
  belongs_to :item

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item
  before_action :move_to_index


  def index
    redirect_to new_card_path and return unless current_user.card.present?
    @order_address = OrderAddress.new
 end

  def create
    @order_address = OrderAddress.new(order_params)
    if @order_address.valid?
      pay_item
      @order_address.save
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def order_params
    params.require(:order_address).permit(:postal_code, :shipping_area_id, :city, :address, :buliding_name, :phone_number).merge(user_id: current_user.id,item_id: params[:item_id] )
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def pay_item

    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    customer_token = current_user.card.customer_token # ログインしているユーザーの顧客トークンを定義
    Payjp::Charge.create(
      amount: @item.price, # 商品の値段
      customer: customer_token, # 顧客のトークン
      currency: 'jpy' # 通貨の種類（日本円）
    )
    end


     def move_to_index
      if current_user.id == @item.user_id || @item.order.present? 
         redirect_to root_path
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<% breadcrumb :order, @item %>
<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    
    <div class='buy-item-info'>
      <%= image_tag @item.images[0], class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.name %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @item.price %></p>
          <p class='item-price-sub-text'><%= @item.shipping_fee.name %></p>
        </div>
      </div>
    </div>
    
  
    
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @item.price %>
      </p>
    </div>
    
    <%= form_with model:@order_address,url: item_orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%= render 'shared/error_messages', model: @order_address %>
    
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :postal_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id ,ShippingArea.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :address, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :buliding_name, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
      <%#  link_to "購入" ,item_orders_path(@item.id),method: :post,class:"buy-red-btn" %>
      <%#  link_to "購入" ,order_item_path(@item.id),method: :post,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>