config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/desearch'
  get 'cards/new'
  get 'users/show'
  get 'messages/new'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'streets', to: 'users/registrations#new_streeet'
    post 'streets', to: 'users/registrations#create_street'
  end
  root to: "items#index"
  resources :items do
   resources :messages, only: :create
   resources :orders, only: [:index,:create]
   collection do
    get 'search'
    get 'research'
    get 'desearch'
    get 'sosearch'
   end
  end
  resources :users, only: [:show, :update]
  resources :cards, only: [:new, :create]
  resources :items, only: :order do
    post 'order', on: :member
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :status
  belongs_to :shipping_fee
  belongs_to :shipping_area
  belongs_to :day_to_ship


  with_options numericality: { other_than: 1 ,message: "--以外を入力して下さい"} do
  validates :category_id 
  validates :status_id
  validates :shipping_fee_id
  validates :shipping_area_id
  validates :day_to_ship_id
  end

  belongs_to :user
  has_one :order
  has_many_attached :images
  has_many :messages
  has_many :item_tag_relations
  has_many :tags, through: :item_tag_relations
  has_one :item_order

  with_options presence: true do
    validates :name
    validates :info
    validates :category_id
    validates :status_id
    validates :shipping_fee_id
    validates :shipping_area_id
    validates :day_to_ship_id
    validates :images
  end

  validates  :price,  presence: true, format: {with: /\A[0-9]+\z/},numericality: { only_integer: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except:[:index,:show]
  before_action :set_item, only: [:edit,:show,:update,:destroy]
  before_action :move_to_index,only: [:edit,:update,:destroy]
  before_action :research_product, only: [:index,:show,:research,:desearch]
  before_action :find_item, only: :order  

  def index
    @items = Item.all.order("created_at DESC")
  end 

  def new
    @item = ItemsTag.new
  end

  def create
    @item = ItemsTag.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
      else
        render :new
    end
  end

  def show
    @message = Message.new
    @messages = @item.messages.includes(:user)
  end

  def edit
  
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def search
    return nil if params[:keyword] == ""
    tag = Tag.where(['tag LIKE ?', "%#{params[:keyword]}%"] )
    render json:{ keyword: tag }
  end

  def research
    @results = @p.result
  end

  def desearch
    @items = Item.all
    set_product_column
    @results = @p.result  # 検索条件にマッチした商品の情報を取得
  end


  def order 
    redirect_to new_card_path and return unless current_user.card.present?

    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] 
    customer_token = current_user.card.customer_token 
    Payjp::Charge.create(
      amount: @item.price, 
      customer: customer_token, 
      currency: 'jpy' 
    )

    ItemOrder.create(item_id: params[:id]) 

    redirect_to root_path

  end



  private

  def item_params
    params.require(:items_tag).permit(:tag, :name, :info, :category_id,:status_id,:shipping_fee_id,:shipping_area_id ,:day_to_ship_id,:price,images: []).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    if current_user.id != @item.user_id || @item.order.present? 
       redirect_to action: :index
    end
  end

  def research_product
    @p = Item.ransack(params[:q])  
  end

  def find_item
    @item = Item.find(params[:id]) 
  end

  def set_product_column
    @item_name = Item.select("name").distinct  
    @item_info = Item.select("info").distinct
    
  end



end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/desearch.html.erb
<% breadcrumb :desearch %>
<%= render "shared/header" %>
<h1>
  商品検索
</h1>
<%= search_form_for @p, url: desearch_items_path do |f| %>
  <%= f.label :name_eq, '商品名' %>
  <%= f.collection_select :name_eq, @item_name, :name, :name,  include_blank: '指定なし' %>
  <br>
  <%= f.label :info_eq, '説明：' %>
    <%= f.collection_select :info_eq, @item_info, :info, :info, include_blank: '指定なし'%>
    <br>
     <%= f.label :category_id_eq, 'カテゴリー：' %>
    <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: '指定なし'%>
    <br>
    <%= f.label :status_id_eq, '商品状態：' %>
    <%= f.collection_select :status_id_eq, Status.all, :id, :name, include_blank: '指定なし'%>
    <br>
    <%= f.label :shipping_fee_id_eq, '配送料：' %>
    <%= f.collection_select :shipping_fee_id_eq, ShippingFee.all, :id, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :shipping_area_id_eq, '発送する場所：' %>
    <%= f.collection_select :shipping_area_id_eq, ShippingArea.all, :id, :name, include_blank: '指定なし'%>
    <br>
    <%= f.label :day_to_ship_eq, '発送までの日数：' %>
    <%= f.collection_select :day_to_ship_id_eq, DayToShip.all, :id, :name, include_blank: '指定なし'%>
    <br>
   <%= f.label :price, '価格：' %>
    <%= f.radio_button :price_lteq, '' %>
    指定なし
    <%= f.radio_button :price_lteq, '1000' %>
    1000円以下
    <%= f.radio_button :price_lteq, '2500' %>
    2500円以下
    <%= f.radio_button :price_lteq, '5000' %>
    5000円以下
    <br> 
  <%= f.submit '検索' %>
<% end %>
<h1>
  検索結果
</h1>
<%# 検索結果の個数で条件分岐 %>
<% if @results.length !=0 %>
<ul class='item-lists'>
    <% @results.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag(item.images[0], class: "item-img")  %>

        
        <% if item.order.present? %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
          
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.shipping_fee.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
           <%item.tags.each do |tag| %>
          <%=tag.tag%>
            <%end%>
        </div>
        <% end %>
        <% end %>
      </li>
      </ul>
<% else %>
  該当する商品はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>

app/views/items/edit.html.erb
<% breadcrumb :edit, @item %>
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with(model: @item,local: true) do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>
  

    
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images,name: 'items_tag[images][]', id:"item_image" %>
      </div>
    </div>
    <div id="image-list"></div>
    
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, name: 'items_tag[name]', class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info,name: 'items_tag[info]', class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>


    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category",name: 'items_tag[category_id]'}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status",name: 'items_tag[status_id]'}) %>
      </div>
    </div>
  

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_id,ShippingFee.all,:id, :name, {}, {class:"select-box", id:"item-shipping-fee-status",name: 'items_tag[shipping_fee_id]'}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id,ShippingArea.all,:id, :name, {}, {class:"select-box", id:"item-prefecture",name: 'items_tag[shipping_area_id]'}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:day_to_ship_id,DayToShip.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery",name: 'items_tag[day_to_ship_id]'}) %>
      </div>
    </div>
  

  
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, name: 'items_tag[price]',class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    

    
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる',item_path(@item.id), class:"back-btn" %>
    </div>
    
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<% if  user_signed_in? %>
<%= link_to 'マイページへ行く', user_path(current_user.id) %>
<% end %>
<div class='main'>

  
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  

  
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          10%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  

  
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  

  
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>


  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      新規投稿商品
    </div>
    <ul class='item-lists'>
    <% @items.each do |item| %>

      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag(item.images[0], class: "item-img")  %>

        
        <% if item.order.present? %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
          
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.shipping_fee.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
           <%item.tags.each do |tag| %>
          <%=tag.tag%>
            <%end%>
        </div>
        <% end %>
        <% end %>
      </li>
      



      <% if @items.length == 0 %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      

    </ul>
  </div>

</div>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
<% breadcrumb :items %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: items_path, local: true do |f| %>

   
    <%= render 'shared/error_messages', model: f.object %>
    

    
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'items_tag[images][]', id: 'item_image' %>
      </div>
    </div>
     <div id="image-list"></div>


    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name , class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    
    タグ
    <div class="tag-field", id='tag-field'>
      <%= f.text_field :tag, class:"input-tag" %>
    </div>

    <div id="search-result">
    </div>
    
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id,Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id,Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    

  
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_id,ShippingFee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id ,ShippingArea.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:day_to_ship_id,DayToShip.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    

    
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    
    
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
  
  
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/research.erb
<% breadcrumb :research %>
<%= render "shared/header" %>
<div class='item-contents'>
    <h2 class='title'>検索結果</h2>
    <div class="subtitle" >
      新規投稿商品
    </div>
    <ul class='item-lists'>
    
    <% @results.each do |item| %>

      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag(item.images[0], class: "item-img")  %>

        
        <% if item.order.present? %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
          
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.shipping_fee.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
           <%item.tags.each do |tag| %>
          <%=tag.tag%>
            <%end%>
        </div>
        <% end %>
        <% end %>
      </li>

app/views/items/show.html.erb
<%= render "shared/header" %>
<% breadcrumb :show, @item %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag(@item.images[0] ,class:"item-box-img") %>
      
      <% if @item.order.present? %>
      <div class="sold-out">
        <span>Sold Out!!</span>
      </div>
      <% end %>
      
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%="¥#{@item.price}"%>
      </span>
      <span class="item-postage">
        <%= @item.shipping_fee.name %>
      </span>
    </div>

    <% if  user_signed_in? && @item.order.blank? %>
      <% if  current_user.id == @item.user_id %>
        <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
      <% else %>
      
        <%= link_to "購入画面に進む", item_orders_path(@item.id) ,class:"item-red-btn"%>
        
      <% end %>
    <% end %>
    

    <div class="item-explain-box">
      <span><%= @item.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname%></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_fee.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.shipping_area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.day_to_ship.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  

  <div class="comment-box">
     <%= form_with(model: [@item, @message]) do |textarea| %>
      <%= textarea.text_area :text, placeholder: "コメントする", class:"comment-text"%></textarea>
      <div id='messages'>
    <% @messages.reverse_each do |message| %>
       <p><%= message.text %></p>
       <% end %>
       </div>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
    <% end %>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>
  
</div>

<%= render "shared/footer" %>